### PR TITLE
feat: add halo2 verifier with custom algorithm

### PR DESCRIPTION
**Pull request by guha-rahul**
addresses #11 , 
I have added the halo2 verifier in this repo using https://github.com/axiom-crypto/halo2-scaffold as a reference.

### CODE REVIEW

**Comment by wraitii** [comment]
Hey @guha-rahul , can you clarify how to use this ?

**Comment by guha-rahul** [comment]
> Hey @guha-rahul , can you clarify how to use this ?
Sorry for the late reply
Assuming we have all the artifacts, it is supposed to `cargo run  main -- --name some_algorithm_in_zk -k <DEGREE> verify`

**Comment by guha-rahul** [comment]
@wraitii hey there, would love to hear further directions on this.

**Comment by wraitii** [comment]
> @wraitii hey there, would love to hear further directions on this.

I guess my question extends to "what do you mean by 'assuming we have all the artifacts' ?
Regardless, I'll proceed with validating your contribution on OD

**Comment by guha-rahul** [comment]
> I guess my question extends to "what do you mean by 'assuming we have all the artifacts' ?

Afai understand we need the proof, the circuit, and the vkey for the proof verification as artifacts.
Also even if i may not be eligible for rewards on this issue , i am looking forward to learn from this and hopefully get it merged .

**Review by wraitii — APPROVED** [review]
Gonna approve this to get you paid on OD, we'll need to restart some work on the main repo after our protocol upgrades

**Comment by guha-rahul** [comment]
@wraitii by the main repo do you mean https://github.com/Hyle-org/hyle ?

**Pull request merged**
